/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ProdutoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;

/**
 *
 * @author assparremberger
 */
public class ListProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListClientes
     */
    public ListProdutos() {
        initComponents();
        carregarTabela();
    }

    private void carregarTabela() {
        List<?> lista;
        DefaultTableModel model = new DefaultTableModel();
        String[] colunas = {"Código", "Nome", "Preco",
            "Quantidade", "Categoria"};
        
        lista = ProdutoDAO.getProdutos();
            
        model.setColumnIdentifiers(colunas);
        
        for (Object prod : lista) {
            Produto produto = (Produto) prod;
                
            Object[] linha = {};
            linha = new Object[]{
                produto.getId(), produto.getNome(),
                produto.getPreco(), produto.getQuantidade(),
                produto.getCategoria().getNome()};
            
            model.addRow( linha );
        }
        
        tableProdutos.setModel( model );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Produtos");

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Maria"},
                {"2", "João"}
            },
            new String [] {
                "Código", "Nome"
            }
        ));
        jScrollPane1.setViewportView(tableProdutos);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnExcluir)
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = tableProdutos.getSelectedRow();   
        if( linha < 0 ){
            JOptionPane.showMessageDialog(this, 
                "Você deve selecionar um cliente!");
        }else{
            int id = (int) tableProdutos.getValueAt(linha, 0);
            String nome = (String) tableProdutos.getValueAt(linha, 1);
            int resposta = JOptionPane.showConfirmDialog(this, 
                    "Confirma a exclusão do produto " + nome + "?", 
                    "Excluir Produto", JOptionPane.YES_NO_OPTION);
            if( resposta == JOptionPane.YES_OPTION ){
                ProdutoDAO.excluir( id );
                carregarTabela();
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProdutos;
    // End of variables declaration//GEN-END:variables
}
